language: node_js
os: linux
node_js:
  - node
  - 'lts/*'
  - '10'
addons:
  apt:
    packages:
    - redis-server
script:
  - '(redis-server & )'
  - 'npm test'
  - 'npm run lint'
cache: npm
notifications:
  email:
    on_success: never
